name: "Spare Grandma"
description: "Indie Music Blog hosted by Michael Core and Dylan Clay"

# Your site's domain goes here (eg: //mmistakes.github.io, http://mademistakes.com, etc)
# When testing locally leave blank or use http://localhost:4000
url: "rachyrach.github.io/sparegrandma"
baseurl: "/sparegrandma"

paginate: 10

future: true
markdown: rdiscount
permalink: pretty
pygments: true


owner:
  name:           Spare Grandma
  avatar:         logo.jpg
  bio:            "Your bio goes here. It shouldn't be super long but a good two sentences or two should suffice."
  email:          you@email.com
  # Social networking links used in footer. Update and remove as you like.
  twitter:        sparegrandma
  facebook:       
  github:         
  stackexchange:  
  linkedin:       
  instagram:      sparegrandma
  flickr:         
  tumblr:         
  # google plus id, include the '+', eg +mmistakes
  google_plus:    +yourid

