name: "Spare Grandma"
description: "Spare Grandma Indie Music Blog. For fans of Pitchfork, Aquarium Drunkard, NPR, and Sirius XMU."

# Your site's domain goes here (eg: //mmistakes.github.io, http://mademistakes.com, etc)
# When testing locally leave blank or use http://localhost:4000
url: "http://sparegrandma.com"
baseurl: ""

paginate: 10

future: true
markdown: rdiscount
permalink: pretty
pygments: true


owner:
  name:           Spare Grandma
  avatar:         logo.jpg
  bio:            "Your bio goes here. It shouldn't be super long but a good two sentences or two should suffice."

  twitter:        sparegrandma 
  instagram:      sparegrandma
  
  
  defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"



