title: "Spare Grandma"
description: "Spare Grandma Indie Music Blog. For fans of Pitchfork, Aquarium Drunkard, NPR, and Sirius XMU."

# Your site's domain goes here (eg: //mmistakes.github.io, http://mademistakes.com, etc)
# When testing locally leave blank or use http://localhost:4000
url: "http://sparegrandma.com"
baseurl: ""

paginate: 10

future: true
markdown: rdiscount
permalink: pretty
pygments: true


owner:
  name:           Spare Grandma
  avatar:         logo.jpg
  bio:            "Spare Grandma Indie Music Blog. For fans of Pitchfork, Aquarium Drunkard, NPR, and Sirius XMU. Broadcasting from College Station and Houston, TX. Tune in at www.kanm.org every Wednesday from 3-5 PM."
  twitter:        sparegrandma 
  instagram:      sparegrandma
  
  
authors:
  michael:
    display_name: Michael Core
    image: http://sparegrandma.com/images/michael.png
    instagram: miggulchor
    bio: "Medical scribe, skateboarder, musician. Fan of Pitchfork, Aquarium Drunkard, KEXP, KANM Student Radio, and Brooklyn Vegan."
  dylan:
    display_name: Dylan Clay
    image: http://sparegrandma.com/images/dylan.png
    instagram: dclay1113
    bio: "College student who dabbles in music on the side. Fan of Pitchfork, Aquarium Drunkard, Passion of The Weiss, Dead End Hip Hop"
  rachel:
    display_name: Rachel Binagia
    image: http://sparegrandma.com/images/rachel.png
    instagram: rrbinag
    bio: "Rachel is a wanna-be musician and an above-average whistler."
    
    



