title: "Spare Grandma"
description: "Spare Grandma Indie Music Blog. For fans of Pitchfork, Aquarium Drunkard, NPR, and Sirius XMU."

# Your site's domain goes here (eg: //mmistakes.github.io, http://mademistakes.com, etc)
# When testing locally leave blank or use http://localhost:4000
# test YAML here http://codebeautify.org/yaml-validator
url: "http://sparegrandma.com"
baseurl: ""

paginate: 10

future: true
markdown: rdiscount
permalink: pretty
pygments: true


owner:
  name:           Spare Grandma
  avatar:         logo.jpg
  bio:            "Spare Grandma Indie Music Blog. For fans of Pitchfork, Aquarium Drunkard, NPR, and Sirius XMU. Broadcasting from College Station and Houston, TX. Tune in at www.kanm.org every Wednesday from 3-5 PM."
  twitter:        sparegrandma 
  instagram:      sparegrandma
  
  
authors:
  michael:
    display_name: Michael Core
    image: http://sparegrandma.com/images/michael.png
    instagram: miggulchor
    spotify: mcore44
    bio: "Medical scribe, skateboarder, musician. Fan of Pitchfork, Aquarium Drunkard, KEXP, KANM Student Radio, and Brooklyn Vegan."
  dylan:
    display_name: Dylan Clay
    image: http://sparegrandma.com/images/dylan.png
    instagram: dclay1113
    spotify: 1229861509
    bio: "College student who dabbles in music on the side. Fan of Pitchfork, Aquarium Drunkard, Passion of The Weiss, Dead End Hip Hop"
  rachel:
    display_name: Rachel Binagia
    image: http://sparegrandma.com/images/rachel.png
    spotify: rrbinag
    instagram: rrbinag
    bio: "Rachel is a wanna-be musician and an above-average whistler."
    
# for youtube add everything after https://www.youtube.com/watch?v= (add this info)  
# save album as album number 

rotation:
  album1:
    album: "VEGA INTL NIGHT SCHOOL"
    artist: Neon Indian
    image: album01.jpg
    youtube: b1JHawvhtrI
    soundcloud: 
    spotify: https://embed.spotify.com/?uri=spotify%3Aalbum%3A5jgrzAcDHJ5Nb2viW52OlR
    link:
  album2:
    album: "Are You Alone?"
    artist: Majical Cloudz
    image: album02.jpg
    youtube: 7yxY2cKsLis&list=PLZqsyBiYZFQ1HuJ_GLL6wjopsy8-hFBy-
    soundcloud: 
    spotify: https://embed.spotify.com/?uri=spotify%3Aalbum%3A2xF3ioefFdZrOg9zUBU5hb  
    link: https://www.youtube.com/playlist?list=PLZqsyBiYZFQ1HuJ_GLL6wjopsy8-hFBy-
  album3:
    album: "Fading Frontier"
    artist: Deerhunter
    image: album03.jpg
    youtube: CG6jk5Q90DA
    soundcloud:
    spotify: https://embed.spotify.com/?uri=spotify%3Aalbum%3A0y5XgOUEiJSSIMxC4ALRAC
    link:
  album4:
    album: "90059"
    artist: Jay Rock
    image: album04.jpg
    youtube: -O4th2sHxdU
    soundcloud:
    spotify: https://embed.spotify.com/?uri=spotify%3Aalbum%3A1fsvlnonD95p6VTEdQ7zJn 
    link:
  album5:
    album: "Divers"
    artist: Joanna Newsom
    image: album05.jpg 
    youtube: 48xlgXqQKLA
    soundcloud:
    spotify:
    link:
  album6: 
    album: "Depression Cherry"
    artist: Beach House
    image: album06.jpg
    youtube: Cy5MiOqarYs
    soundcloud:
    spotify: https://embed.spotify.com/?uri=spotify%3Aalbum%3A35vTE3hx3AAXtM6okpJIIt
    link:
  album7:
    album: "So the Flies Don't Come"
    artist: Milo
    image: album07.jpg
    youtube: P5H77IUvu1E
    soundcloud:
    spotify: https://embed.spotify.com/?uri=spotify%3Aalbum%3A1aCdrqjxp4duqTRne80ecY 
    link:
  album8:
    album: "Meow the Jewels"
    artist: Run The Jewels
    image: album08.jpg
    youtube: eOvzllwBJQg&list=PLQx7Olx-4qKiS3gzbNn9yEEZXbQ-bb9ab
    soundcloud:
    spotify: https://embed.spotify.com/?uri=spotify%3Aalbum%3A0YHFRaVnIWPj0gJWvlAoxE
    link:
  album9:
    album: "New Bermuda"
    artist: Deafheaven
    image: album09.jpg
    youtube: https://www.youtube.com/watch?v=iezyTjg-8iY
    soundcloud:
    spotify: https://embed.spotify.com/?uri=spotify%3Aalbum%3A2e4xOasRFhJn4x2MBM5pdu 
    link:
  album10:
    album: "The Agent Intellect"
    artist: Protomartyr
    image: album10.jpg
    youtube: https://www.youtube.com/watch?v=ZB_VPDXAhKU
    soundcloud:
    spotify: https://embed.spotify.com/?uri=spotify%3Aalbum%3A3oNSWUAqB7CCTSH1zdlrXO
    link:
  album11:
    album: "Sun Coming Down"
    artist: Ought
    image: album11.jpg
    youtube: https://www.youtube.com/watch?v=O2cd8T1oO_0&list=PLsLK3KowwXTjJX6GeYKb6ULN2dkbF2R28
    soundcloud:
    spotify: https://embed.spotify.com/?uri=spotify%3Aalbum%3A6Il9jwREmViqtjAXbkprVA
    link:
  album12:
    album: "Dry Food"
    artist: Pale Hound
    image: album12.jpg
    youtube: https://www.youtube.com/watch?v=a-jzuHhVfnc&list=PLnkHHIr2NOf4jgZ1bRaBzvFfge1FvcyOC
    soundcloud:
    spotify: https://embed.spotify.com/?uri=spotify%3Aalbum%3A55vUt9yY45eIvnxUUqTnj6
    link:


